### ISSUE TITLE
Missing Xiaomi products

### ISSUE THREAD

**Issue by Neustradamus** [yuos-bit/Padavan#2]
Dear @yuos-bit,

Can you add other Xiaomi products?
- https://openwrt.org/ru/toh/xiaomi/start
- https://deviwiki.com/wiki/List_of_Xiaomi_Wireless_Devices

Thanks in advance.

**Comment by yuos-bit** [comment]
I'm sorry, because there is no other Xiaomi router equipment in hand that can be used for debugging and testing, and no other friends are willing to assist in the test. Also, I am currently busy at work, so I am sorry, there is no plan to adapt to other models of Xiaomi router at the moment. There won't be. It is recommended that you can git clone my factory library and adapt it according to your needs.
